# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"\x1b\n\x0cJsonWebToken\x12\x0b\n\x03jwt\x18\x01 \x01(\t\"_\n\x04User\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_level\x18\x05 \x01(\x05\"\xc5\x01\n\x08Resource\x12%\n\x06method\x18\x01 \x01(\x0e\x32\x15.auth.Resource.Method\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0b\n\x03jwt\x18\x03 \x01(\t\"w\n\x06Method\x12\x0b\n\x07INVALID\x10\x00\x12\x07\n\x03GET\x10\x01\x12\x08\n\x04POST\x10\x02\x12\x07\n\x03PUT\x10\x03\x12\n\n\x06\x44\x45LETE\x10\x04\x12\x08\n\x04HEAD\x10\x05\x12\x0b\n\x07\x43ONNECT\x10\x06\x12\x0b\n\x07OPTIONS\x10\x07\x12\t\n\x05TRACE\x10\x08\x12\t\n\x05PATCH\x10\t\"\x1c\n\x06\x41\x63\x63\x65ss\x12\x12\n\nhas_access\x18\x01 \x01(\x08\x32\x63\n\x0b\x41uthService\x12)\n\tHasAccess\x12\x0e.auth.Resource\x1a\x0c.auth.Access\x12)\n\x07GetUser\x12\x12.auth.JsonWebToken\x1a\n.auth.Userb\x06proto3')



_JSONWEBTOKEN = DESCRIPTOR.message_types_by_name['JsonWebToken']
_USER = DESCRIPTOR.message_types_by_name['User']
_RESOURCE = DESCRIPTOR.message_types_by_name['Resource']
_ACCESS = DESCRIPTOR.message_types_by_name['Access']
_RESOURCE_METHOD = _RESOURCE.enum_types_by_name['Method']
JsonWebToken = _reflection.GeneratedProtocolMessageType('JsonWebToken', (_message.Message,), {
  'DESCRIPTOR' : _JSONWEBTOKEN,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.JsonWebToken)
  })
_sym_db.RegisterMessage(JsonWebToken)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.User)
  })
_sym_db.RegisterMessage(User)

Resource = _reflection.GeneratedProtocolMessageType('Resource', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCE,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.Resource)
  })
_sym_db.RegisterMessage(Resource)

Access = _reflection.GeneratedProtocolMessageType('Access', (_message.Message,), {
  'DESCRIPTOR' : _ACCESS,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.Access)
  })
_sym_db.RegisterMessage(Access)

_AUTHSERVICE = DESCRIPTOR.services_by_name['AuthService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JSONWEBTOKEN._serialized_start=20
  _JSONWEBTOKEN._serialized_end=47
  _USER._serialized_start=49
  _USER._serialized_end=144
  _RESOURCE._serialized_start=147
  _RESOURCE._serialized_end=344
  _RESOURCE_METHOD._serialized_start=225
  _RESOURCE_METHOD._serialized_end=344
  _ACCESS._serialized_start=346
  _ACCESS._serialized_end=374
  _AUTHSERVICE._serialized_start=376
  _AUTHSERVICE._serialized_end=475
# @@protoc_insertion_point(module_scope)
